pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot-preview[bot]
      - '#approved-reviews-by>=1'
      - 'status-success=LGTM analysis: JavaScript'
      - status-success=netlify/avocadotoast/deploy-preview
    actions:
      merge:
        method: squash
      delete_head_branch: