[build]
  command = "yarn build"
  publish = "_site/"


[[redirects]]
  from = "/episodes/1"
  to = "https://www.ximalaya.com/keji/29161862/211907713"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/1"
  to = "https://anchor.fm/avocado-toast/episodes/iPhone-11-e5bndl"
  status = 302

[[redirects]]
  from = "/episodes/2"
  to = "https://www.ximalaya.com/keji/29161862/213299232"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/2"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e5ena7"
  status = 302

[[redirects]]
  from = "/episodes/3"
  to = "https://www.ximalaya.com/keji/29161862/215110367"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/3"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e5j2kc"
  status = 302

[[redirects]]
  from = "/episodes/4"
  to = "https://www.ximalaya.com/keji/29161862/216501215"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/4"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e5oiht"
  status = 302

[[redirects]]
  from = "/episodes/5"
  to = "https://www.ximalaya.com/keji/29161862/218698604"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/5"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e6fnaq"
  status = 302

[[redirects]]
  from = "/episodes/6"
  to = "https://www.ximalaya.com/keji/29161862/220081838"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/6"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e7p07r"
  status = 302

[[redirects]]
  from = "/episodes/7"
  to = "https://www.ximalaya.com/keji/29161862/222067054"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/7"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e81d5t"
  status = 302

[[redirects]]
  from = "/episodes/8"
  to = "https://www.ximalaya.com/keji/29161862/224232247"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/8"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e8edad"
  status = 302

[[redirects]]
  from = "/episodes/9"
  to = "https://www.ximalaya.com/keji/29161862/226505145"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/9"
  to = "https://anchor.fm/avocado-toast/episodes/BlizzCon-2019-e8sbr4"
  status = 302

[[redirects]]
  from = "/episodes/10"
  to = "https://www.ximalaya.com/keji/29161862/228225386"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/10"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e8vpel"
  status = 302

[[redirects]]
  from = "/episodes/11"
  to = "https://www.ximalaya.com/keji/29161862/229962268"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/11"
  to = "https://anchor.fm/avocado-toast/episodes/CPU-e93dn5"
  status = 302

[[redirects]]
  from = "/episodes/12"
  to = "https://www.ximalaya.com/keji/29161862/232239607"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/12"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e97p4b"
  status = 302

[[redirects]]
  from = "/episodes/13"
  to = "https://www.ximalaya.com/keji/29161862/234280306"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/13"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e9blb9"
  status = 302

[[redirects]]
  from = "/episodes/14"
  to = "https://www.ximalaya.com/keji/29161862/235814021"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/14"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e9f4u8"
  status = 302

[[redirects]]
  from = "/*"
  to = "https://www.ximalaya.com/keji/29161862/"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/*"
  to = "https://anchor.fm/avocado-toast/"
  status = 302
