[build]
  command = "yarn build"
  publish = "_site/"

[[redirects]]
  from = "/*"
  to = "/cn/:splat"
  status = 302
  conditions = {Country = ["CN"]}
  force = true

[[redirects]]
  from = "/cn/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/us/:splat"
  status = 302
  conditions = {Country = ["US"]}
  force = true

[[redirects]]
  from = "/us/*"
  to = "/:splat"
  status = 200
  force = true

[[redirects]]
  from = "https://avocadotoast.netlify.com/*"
  to = "https://avocadotoast.live/:splat"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404

[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/episodes/:placeholder/"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
