[build]
  command = "yarn build"
  publish = "_site/"


[[redirects]]
  from = "/episodes/1"
  to = "https://www.ximalaya.com/keji/29161862/211907713"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/1"
  to = "https://anchor.fm/avocado-toast/episodes/iPhone-11-e5bndl"
  status = 302

[[redirects]]
  from = "/episodes/2"
  to = "https://www.ximalaya.com/keji/29161862/213299232"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/2"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e5ena7"
  status = 302

[[redirects]]
  from = "/episodes/3"
  to = "https://www.ximalaya.com/keji/29161862/215110367"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/3"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e5j2kc"
  status = 302

[[redirects]]
  from = "/episodes/4"
  to = "https://www.ximalaya.com/keji/29161862/216501215"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/4"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e5oiht"
  status = 302

[[redirects]]
  from = "/episodes/5"
  to = "https://www.ximalaya.com/keji/29161862/218698604"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/5"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e6fnaq"
  status = 302

[[redirects]]
  from = "/episodes/6"
  to = "https://www.ximalaya.com/keji/29161862/220081838"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/6"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e7p07r"
  status = 302

[[redirects]]
  from = "/episodes/7"
  to = "https://www.ximalaya.com/keji/29161862/222067054"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/7"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e81d5t"
  status = 302

[[redirects]]
  from = "/episodes/8"
  to = "https://www.ximalaya.com/keji/29161862/224232247"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/8"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e8edad"
  status = 302

[[redirects]]
  from = "/episodes/9"
  to = "https://www.ximalaya.com/keji/29161862/226505145"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/9"
  to = "https://anchor.fm/avocado-toast/episodes/BlizzCon-2019-e8sbr4"
  status = 302

[[redirects]]
  from = "/episodes/10"
  to = "https://www.ximalaya.com/keji/29161862/228225386"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/10"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e8vpel"
  status = 302

[[redirects]]
  from = "/episodes/11"
  to = "https://www.ximalaya.com/keji/29161862/229962268"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/11"
  to = "https://anchor.fm/avocado-toast/episodes/CPU-e93dn5"
  status = 302

[[redirects]]
  from = "/episodes/12"
  to = "https://www.ximalaya.com/keji/29161862/232239607"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/12"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e97p4b"
  status = 302

[[redirects]]
  from = "/episodes/13"
  to = "https://www.ximalaya.com/keji/29161862/234280306"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/13"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e9blb9"
  status = 302

[[redirects]]
  from = "/episodes/14"
  to = "https://www.ximalaya.com/keji/29161862/235814021"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/14"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e9f4u8"
  status = 302

[[redirects]]
  from = "/episodes/15"
  to = "https://www.ximalaya.com/keji/29161862/237387581"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/15"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e9fuh4"
  status = 302

[[redirects]]
  from = "/episodes/16"
  to = "https://www.ximalaya.com/keji/29161862/239183695"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/16"
  to = "https://anchor.fm/avocado-toast/episodes/ep-e9gbip"
  status = 302

[[redirects]]
  from = "/episodes/17"
  to = "https://www.ximalaya.com/keji/29161862/240816707"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/17"
  to = "https://anchor.fm/avocado-toast/episodes/AMA-e9trj5"
  status = 302

[[redirects]]
  from = "/episodes/18"
  to = "https://www.ximalaya.com/keji/29161862/242955091"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/18"
  to = "https://anchor.fm/avocado-toast/episodes/ep-ea3u4o"
  status = 302

[[redirects]]
  from = "/episodes/19"
  to = "https://www.ximalaya.com/keji/29161862/244067685"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/19"
  to = "https://anchor.fm/avocado-toast/episodes/ep-ea5tm9"
  status = 302

[[redirects]]
  from = "/episodes/20"
  to = "https://www.ximalaya.com/keji/29161862/245726165"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/20"
  to = "https://anchor.fm/avocado-toast/episodes/CES-eaalvv"
  status = 302

[[redirects]]
  from = "/episodes/21"
  to = "https://www.ximalaya.com/keji/29161862/245880218"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/21"
  to = "https://anchor.fm/avocado-toast/episodes/ep-eab68q"
  status = 302

[[redirects]]
  from = "/episodes/22"
  to = "https://www.ximalaya.com/keji/29161862/250507151"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/22"
  to = "https://anchor.fm/avocado-toast/episodes/CES-ealr57"
  status = 302

[[redirects]]
  from = "/episodes/23"
  to = "https://www.ximalaya.com/keji/29161862/253434683"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/23"
  to = "https://anchor.fm/avocado-toast/episodes/ep-eaq9hj"
  status = 302

[[redirects]]
  from = "/episodes/24"
  to = "https://www.ximalaya.com/keji/29161862/257922865"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/24"
  to = "https://anchor.fm/avocado-toast/episodes/ep-eb0gge"
  status = 302

[[redirects]]
  from = "/episodes/25"
  to = "https://www.ximalaya.com/keji/29161862/258432175"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/25"
  to = "https://anchor.fm/avocado-toast/episodes/ep-eb0os0"
  status = 302

[[redirects]]
  from = "/episodes/26"
  to = "https://www.ximalaya.com/keji/29161862/263735265"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/26"
  to = "https://anchor.fm/avocado-toast/episodes/ep-eb9474"
  status = 302

[[redirects]]
  from = "/episodes/27"
  to = "https://www.ximalaya.com/keji/29161862/265703043"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/27"
  to = "https://anchor.fm/avocado-toast/episodes/ep-ebcvvi"
  status = 302

[[redirects]]
  from = "/episodes/28"
  to = "https://www.ximalaya.com/keji/29161862/270271030"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/episodes/28"
  to = "https://anchor.fm/avocado-toast/episodes/ep-ebkgv3"
  status = 302

[[redirects]]
  from = "/*"
  to = "https://www.ximalaya.com/keji/29161862/"
  status = 302
  conditions = {Country = ["CN"]}

[[redirects]]
  from = "/*"
  to = "https://anchor.fm/avocado-toast/"
  status = 302
